### ISSUE TITLE
Solver panics with singular matrices

### ISSUE THREAD

**Issue by QTi1** [Specy/microlp#5]
I have a rather complex linear program, and microlp tends to panic in line 1415 of `solver.rs` due to a singular matrix (other solvers have similar issues with the same input). I see there's a TODO comment there, and my example is too complicated to be able to explain when a singular basis matrix is possible, other than saying that it is possible. 😅 It would be nice to propagate the error instead of panicking there (I'm currently having to use `catch_unwind` to deal with it).

**Comment by Specy** [comment]
Hello! Sorry for the late reply, I just saw the issue

Yes I saw this issue on minilp too, this must be addressed by removing all the unwraps and improving the reported errors. I'll try working on it those days!

**Comment by Specy** [comment]
Could you check if this solves your issue? i have not yet published a new release so use the [create from git](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)

**Comment by QTi1** [comment]
I was using `microlp` within `good_lp`, and the new `enum` variant broke a `match` statement, making this fix a breaking change. When I manually changed the `good_lp` to make it compile, it handles the error properly and nothing panics :)

**Comment by Specy** [comment]
Yes I was considering if either reporting this with the existing Internal error variant or creating a new variant for this specific error. 

Is it useful to know that there was a specific Singular matrix error?

**Comment by QTi1** [comment]
It's not that useful as a distinct error on my end; in my case, I only really need to know whether it succeeded or not.

**Comment by Specy** [comment]
Ok thank you for testing it out! I'll publish a new version tomorrow and also update good_lp

**Comment by Specy** [comment]
@QTi1 I published a new version `0.2.7` without the breaking change! let me know if it's all good

**Comment by Bobitsmagic** [comment]
Hey i have a similar issue. I have a very simple linear program and on some instances of it i get the singular matrix error. 

What does that actually mean in terms of the LP? Does it mean the system is underdetermined? Do i need to change formulation to fix this?

I could not find anything online regarding singular matrices in LPs thats why i am asking here.

![Image](https://github.com/user-attachments/assets/bf9f1305-9ddc-4531-af43-24127cc587df)

For some choices of y_sc it returns the Singular matrix error upon solving and i dont understand why.

**Comment by Specy** [comment]
@Bobitsmagic the creator of this issue mentioned that they had this issue with other solvers too, could you test to check if it happens using other solvers?

You could try to write it in https://rooc.specy.app/ and try to solve it with the "Highs solver" which will use highs, and then try with "Milp solver" which uses microlp

Or if you are using good_lp with it, just switch solver backend

**Comment by Specy** [comment]
> Anyways thank you for your help. If you want i can send you the LPs that resulted in the singular matrix error.
Sure! Make a new issue about it
